### ISSUE TITLE
Does not work when a case is running

### ISSUE THREAD

**Issue by kaldras** [projectcaluma/caluma-interval#63]
The logic of the `handle_form` or `get_last_run` functions seems to be wrong. They will iterate over the found forms with intervals and stop handling forms (starting cases) a soon as one form has a `RUNNING` case. But this should be handle per form. For example:

Two forms with intervals
* form1
* form2

Existing case (**RUNNING**) with a document based on **form1**.

Expected:
*caluma_interval* should not start a case for **form1** but should start a case for **form2**.

Current:
No case will be started because one is running for **form1**

**Comment by open-dynaMIX** [comment]
@kaldras That's strange! I've added a test for this in #66 and it passes. Also when looking at the code, this can't really happen.

Could it be related to #64? So the interval logic is not run at all after throwing the exeption.

**Comment by open-dynaMIX** [comment]
I've just opened #67, because that's something we need to handle anyway.

**Comment by kaldras** [comment]
I will close this since the problem was in some cases the exception which was thrown, but this is fixed through #67 and in other instances it was a problem of visibility and permission of the caluma project itself and not the caluma-interval.

Thanks for digging in to this and adding the test!
